// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/auction.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BidRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`       // unique auction ID
	PlacementId   string                 `protobuf:"bytes,2,opt,name=placement_id,json=placementId,proto3" json:"placement_id,omitempty"` // ad slot identifier
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FloorPrice    float64                `protobuf:"fixed64,4,opt,name=floor_price,json=floorPrice,proto3" json:"floor_price,omitempty"` // minimum acceptable CPM
	Candidates    []*Candidate           `protobuf:"bytes,5,rep,name=candidates,proto3" json:"candidates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BidRequest) Reset() {
	*x = BidRequest{}
	mi := &file_proto_auction_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BidRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BidRequest) ProtoMessage() {}

func (x *BidRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auction_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BidRequest.ProtoReflect.Descriptor instead.
func (*BidRequest) Descriptor() ([]byte, []int) {
	return file_proto_auction_proto_rawDescGZIP(), []int{0}
}

func (x *BidRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *BidRequest) GetPlacementId() string {
	if x != nil {
		return x.PlacementId
	}
	return ""
}

func (x *BidRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *BidRequest) GetFloorPrice() float64 {
	if x != nil {
		return x.FloorPrice
	}
	return 0
}

func (x *BidRequest) GetCandidates() []*Candidate {
	if x != nil {
		return x.Candidates
	}
	return nil
}

type Candidate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AdId          string                 `protobuf:"bytes,1,opt,name=ad_id,json=adId,proto3" json:"ad_id,omitempty"`
	AdvertiserId  string                 `protobuf:"bytes,2,opt,name=advertiser_id,json=advertiserId,proto3" json:"advertiser_id,omitempty"`
	BidCpm        float64                `protobuf:"fixed64,3,opt,name=bid_cpm,json=bidCpm,proto3" json:"bid_cpm,omitempty"`                   // advertiser bid in CPM (cost per mille)
	PredictedCtr  float64                `protobuf:"fixed64,4,opt,name=predicted_ctr,json=predictedCtr,proto3" json:"predicted_ctr,omitempty"` // model score [0,1]
	DailyBudget   float64                `protobuf:"fixed64,5,opt,name=daily_budget,json=dailyBudget,proto3" json:"daily_budget,omitempty"`    // advertiser daily budget USD
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Candidate) Reset() {
	*x = Candidate{}
	mi := &file_proto_auction_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Candidate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Candidate) ProtoMessage() {}

func (x *Candidate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auction_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Candidate.ProtoReflect.Descriptor instead.
func (*Candidate) Descriptor() ([]byte, []int) {
	return file_proto_auction_proto_rawDescGZIP(), []int{1}
}

func (x *Candidate) GetAdId() string {
	if x != nil {
		return x.AdId
	}
	return ""
}

func (x *Candidate) GetAdvertiserId() string {
	if x != nil {
		return x.AdvertiserId
	}
	return ""
}

func (x *Candidate) GetBidCpm() float64 {
	if x != nil {
		return x.BidCpm
	}
	return 0
}

func (x *Candidate) GetPredictedCtr() float64 {
	if x != nil {
		return x.PredictedCtr
	}
	return 0
}

func (x *Candidate) GetDailyBudget() float64 {
	if x != nil {
		return x.DailyBudget
	}
	return 0
}

type AuctionResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	WinnerAdId    string                 `protobuf:"bytes,2,opt,name=winner_ad_id,json=winnerAdId,proto3" json:"winner_ad_id,omitempty"`
	WinnerAdvId   string                 `protobuf:"bytes,3,opt,name=winner_adv_id,json=winnerAdvId,proto3" json:"winner_adv_id,omitempty"`
	ClearingPrice float64                `protobuf:"fixed64,4,opt,name=clearing_price,json=clearingPrice,proto3" json:"clearing_price,omitempty"` // second price in CPM
	Ecpm          float64                `protobuf:"fixed64,5,opt,name=ecpm,proto3" json:"ecpm,omitempty"`                                        // winner eCPM = bid × CTR
	BudgetCapped  bool                   `protobuf:"varint,6,opt,name=budget_capped,json=budgetCapped,proto3" json:"budget_capped,omitempty"`     // true if winner was budget-throttled
	FloorEnforced bool                   `protobuf:"varint,7,opt,name=floor_enforced,json=floorEnforced,proto3" json:"floor_enforced,omitempty"`  // true if floor filtered any candidates
	CandidatesIn  int32                  `protobuf:"varint,8,opt,name=candidates_in,json=candidatesIn,proto3" json:"candidates_in,omitempty"`     // total candidates received
	CandidatesOut int32                  `protobuf:"varint,9,opt,name=candidates_out,json=candidatesOut,proto3" json:"candidates_out,omitempty"`  // candidates passing budget + floor
	LatencyUs     int64                  `protobuf:"varint,10,opt,name=latency_us,json=latencyUs,proto3" json:"latency_us,omitempty"`             // auction latency in microseconds
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuctionResult) Reset() {
	*x = AuctionResult{}
	mi := &file_proto_auction_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuctionResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuctionResult) ProtoMessage() {}

func (x *AuctionResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auction_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuctionResult.ProtoReflect.Descriptor instead.
func (*AuctionResult) Descriptor() ([]byte, []int) {
	return file_proto_auction_proto_rawDescGZIP(), []int{2}
}

func (x *AuctionResult) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *AuctionResult) GetWinnerAdId() string {
	if x != nil {
		return x.WinnerAdId
	}
	return ""
}

func (x *AuctionResult) GetWinnerAdvId() string {
	if x != nil {
		return x.WinnerAdvId
	}
	return ""
}

func (x *AuctionResult) GetClearingPrice() float64 {
	if x != nil {
		return x.ClearingPrice
	}
	return 0
}

func (x *AuctionResult) GetEcpm() float64 {
	if x != nil {
		return x.Ecpm
	}
	return 0
}

func (x *AuctionResult) GetBudgetCapped() bool {
	if x != nil {
		return x.BudgetCapped
	}
	return false
}

func (x *AuctionResult) GetFloorEnforced() bool {
	if x != nil {
		return x.FloorEnforced
	}
	return false
}

func (x *AuctionResult) GetCandidatesIn() int32 {
	if x != nil {
		return x.CandidatesIn
	}
	return 0
}

func (x *AuctionResult) GetCandidatesOut() int32 {
	if x != nil {
		return x.CandidatesOut
	}
	return 0
}

func (x *AuctionResult) GetLatencyUs() int64 {
	if x != nil {
		return x.LatencyUs
	}
	return 0
}

type BudgetStatus struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AdvertiserId    string                 `protobuf:"bytes,1,opt,name=advertiser_id,json=advertiserId,proto3" json:"advertiser_id,omitempty"`
	RemainingBudget float64                `protobuf:"fixed64,2,opt,name=remaining_budget,json=remainingBudget,proto3" json:"remaining_budget,omitempty"`
	SpendRate       float64                `protobuf:"fixed64,3,opt,name=spend_rate,json=spendRate,proto3" json:"spend_rate,omitempty"` // tokens/sec
	Throttled       bool                   `protobuf:"varint,4,opt,name=throttled,proto3" json:"throttled,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *BudgetStatus) Reset() {
	*x = BudgetStatus{}
	mi := &file_proto_auction_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BudgetStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BudgetStatus) ProtoMessage() {}

func (x *BudgetStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auction_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BudgetStatus.ProtoReflect.Descriptor instead.
func (*BudgetStatus) Descriptor() ([]byte, []int) {
	return file_proto_auction_proto_rawDescGZIP(), []int{3}
}

func (x *BudgetStatus) GetAdvertiserId() string {
	if x != nil {
		return x.AdvertiserId
	}
	return ""
}

func (x *BudgetStatus) GetRemainingBudget() float64 {
	if x != nil {
		return x.RemainingBudget
	}
	return 0
}

func (x *BudgetStatus) GetSpendRate() float64 {
	if x != nil {
		return x.SpendRate
	}
	return 0
}

func (x *BudgetStatus) GetThrottled() bool {
	if x != nil {
		return x.Throttled
	}
	return false
}

type BudgetStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AdvertiserId  string                 `protobuf:"bytes,1,opt,name=advertiser_id,json=advertiserId,proto3" json:"advertiser_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BudgetStatusRequest) Reset() {
	*x = BudgetStatusRequest{}
	mi := &file_proto_auction_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BudgetStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BudgetStatusRequest) ProtoMessage() {}

func (x *BudgetStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auction_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BudgetStatusRequest.ProtoReflect.Descriptor instead.
func (*BudgetStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_auction_proto_rawDescGZIP(), []int{4}
}

func (x *BudgetStatusRequest) GetAdvertiserId() string {
	if x != nil {
		return x.AdvertiserId
	}
	return ""
}

var File_proto_auction_proto protoreflect.FileDescriptor

const file_proto_auction_proto_rawDesc = "" +
	"\n" +
	"\x13proto/auction.proto\x12\aauction\"\xbc\x01\n" +
	"\n" +
	"BidRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12!\n" +
	"\fplacement_id\x18\x02 \x01(\tR\vplacementId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x1f\n" +
	"\vfloor_price\x18\x04 \x01(\x01R\n" +
	"floorPrice\x122\n" +
	"\n" +
	"candidates\x18\x05 \x03(\v2\x12.auction.CandidateR\n" +
	"candidates\"\xa6\x01\n" +
	"\tCandidate\x12\x13\n" +
	"\x05ad_id\x18\x01 \x01(\tR\x04adId\x12#\n" +
	"\radvertiser_id\x18\x02 \x01(\tR\fadvertiserId\x12\x17\n" +
	"\abid_cpm\x18\x03 \x01(\x01R\x06bidCpm\x12#\n" +
	"\rpredicted_ctr\x18\x04 \x01(\x01R\fpredictedCtr\x12!\n" +
	"\fdaily_budget\x18\x05 \x01(\x01R\vdailyBudget\"\xe6\x02\n" +
	"\rAuctionResult\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12 \n" +
	"\fwinner_ad_id\x18\x02 \x01(\tR\n" +
	"winnerAdId\x12\"\n" +
	"\rwinner_adv_id\x18\x03 \x01(\tR\vwinnerAdvId\x12%\n" +
	"\x0eclearing_price\x18\x04 \x01(\x01R\rclearingPrice\x12\x12\n" +
	"\x04ecpm\x18\x05 \x01(\x01R\x04ecpm\x12#\n" +
	"\rbudget_capped\x18\x06 \x01(\bR\fbudgetCapped\x12%\n" +
	"\x0efloor_enforced\x18\a \x01(\bR\rfloorEnforced\x12#\n" +
	"\rcandidates_in\x18\b \x01(\x05R\fcandidatesIn\x12%\n" +
	"\x0ecandidates_out\x18\t \x01(\x05R\rcandidatesOut\x12\x1d\n" +
	"\n" +
	"latency_us\x18\n" +
	" \x01(\x03R\tlatencyUs\"\x9b\x01\n" +
	"\fBudgetStatus\x12#\n" +
	"\radvertiser_id\x18\x01 \x01(\tR\fadvertiserId\x12)\n" +
	"\x10remaining_budget\x18\x02 \x01(\x01R\x0fremainingBudget\x12\x1d\n" +
	"\n" +
	"spend_rate\x18\x03 \x01(\x01R\tspendRate\x12\x1c\n" +
	"\tthrottled\x18\x04 \x01(\bR\tthrottled\":\n" +
	"\x13BudgetStatusRequest\x12#\n" +
	"\radvertiser_id\x18\x01 \x01(\tR\fadvertiserId2\x93\x01\n" +
	"\x0eAuctionService\x129\n" +
	"\n" +
	"RunAuction\x12\x13.auction.BidRequest\x1a\x16.auction.AuctionResult\x12F\n" +
	"\x0fGetBudgetStatus\x12\x1c.auction.BudgetStatusRequest\x1a\x15.auction.BudgetStatusB4Z2github.com/saitejasrivilli/ad-auction-engine/protob\x06proto3"

var (
	file_proto_auction_proto_rawDescOnce sync.Once
	file_proto_auction_proto_rawDescData []byte
)

func file_proto_auction_proto_rawDescGZIP() []byte {
	file_proto_auction_proto_rawDescOnce.Do(func() {
		file_proto_auction_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_auction_proto_rawDesc), len(file_proto_auction_proto_rawDesc)))
	})
	return file_proto_auction_proto_rawDescData
}

var file_proto_auction_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_auction_proto_goTypes = []any{
	(*BidRequest)(nil),          // 0: auction.BidRequest
	(*Candidate)(nil),           // 1: auction.Candidate
	(*AuctionResult)(nil),       // 2: auction.AuctionResult
	(*BudgetStatus)(nil),        // 3: auction.BudgetStatus
	(*BudgetStatusRequest)(nil), // 4: auction.BudgetStatusRequest
}
var file_proto_auction_proto_depIdxs = []int32{
	1, // 0: auction.BidRequest.candidates:type_name -> auction.Candidate
	0, // 1: auction.AuctionService.RunAuction:input_type -> auction.BidRequest
	4, // 2: auction.AuctionService.GetBudgetStatus:input_type -> auction.BudgetStatusRequest
	2, // 3: auction.AuctionService.RunAuction:output_type -> auction.AuctionResult
	3, // 4: auction.AuctionService.GetBudgetStatus:output_type -> auction.BudgetStatus
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_auction_proto_init() }
func file_proto_auction_proto_init() {
	if File_proto_auction_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_auction_proto_rawDesc), len(file_proto_auction_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_auction_proto_goTypes,
		DependencyIndexes: file_proto_auction_proto_depIdxs,
		MessageInfos:      file_proto_auction_proto_msgTypes,
	}.Build()
	File_proto_auction_proto = out.File
	file_proto_auction_proto_goTypes = nil
	file_proto_auction_proto_depIdxs = nil
}
